version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URI=postgres://admin:adminpassword@db:5432/couponsystem?sslmode=disable
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/swagger/index.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 
  db:
    image: postgres:16.3
    container_name: postgres-couponsystem-db
    environment:
      POSTGRES_DB: couponsystem
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: